server:
  port: 80

spring:
  application:
    name: spring-ssr
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/spring-ssr
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true